"""add image_url_desktop and image_url_mobile to project

Revision ID: 6dafdb7ec787
Revises: e751e7264c92
Create Date: 2025-10-22 13:27:52.427783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6dafdb7ec787'
down_revision: Union[str, Sequence[str], None] = 'e751e7264c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_url_desktop', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('image_url_mobile', sa.String(length=255), nullable=True))
    op.drop_column('project', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True))
    op.drop_column('project', 'image_url_mobile')
    op.drop_column('project', 'image_url_desktop')
    # ### end Alembic commands ###
